name: Datasette
version: "0.1.10"
slug: datasette
description: Browse SQLite databases with Datasette
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ingress: true
ingress_port: 8001
panel_icon: mdi:database
init: false
ports:
  8001/tcp: 8001
schema:
  port: int?
  db_file: str?
options:
  port: 8001
  db_file: /homeassistant/home-assistant_v2.db
