name: "Datasette"
description: "Explore and publish your Home Assistant database"
version: "0.2.0"
slug: "datasette"
init: false

# Specify the architectures this addon supports.
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

# Auto start the addon when Home Assistant starts
boot: "auto"
startup: "application"

# Use host networking. This makes the port you configure below
# directly available on your Home Assistant host's IP address.
host_network: true

# Add a configuration option for the port.
# You can change this value on the addon's "Configuration" tab.
options:
  port: 8001
schema:
  port: port

# Map the Home Assistant /config directory into the addon at /config
# This is crucial for accessing the database file.
map:
  - "config:ro"

# Optional: Add a link to the project's homepage
url: "https://datasette.io/"